### PR TITLE
Little numbers

### PR DESCRIPTION
**Pull request by a-bzzzz**
When a user clicks a constraint row it will be highlighted in yellow and the related values will be shown in the Sudoku grid in the constrained related cells (squares) with small numbers (negatives in red, non-negatives in blue).

### CODE REVIEW

**Review by ArcticCoder — CHANGES_REQUESTED** [review]
The way the indices are handled right now doesn't work. The clicked index becomes invalid as soon as the filtering changes, but this is not handled in the code, leading to panics. Example:

1.  Start program
2. Solve empty sudoku
3.  Click a constraint
4.  Filter with a max length of 5
5. Line 27 of sudoku_grid.rs panics with an index-out-of-bounds

Additionally
- The numbers seem very small to me, even more so when considering a lecture-type setting.
-  src/gui/constraint_list.rs:170 contains commented-out code for no apparent reason


Basic functionality seems good, after these changes :D

**Comment by pavezzo** [comment]
> The way the indices are handled right now doesn't work. The clicked index becomes invalid as soon as the filtering changes, but this is not handled in the code, leading to panics. Example:
> 
>     1. Start program
> 
>     2. Solve empty sudoku
> 
>     3. Click a constraint
> 
>     4. Filter with a max length of 5
> 
>     5. Line 27 of sudoku_grid.rs panics with an index-out-of-bounds
> 
> 
> Additionally
> 
>     * The numbers seem very small to me, even more so when considering a lecture-type setting.
> 
>     * src/gui/constraint_list.rs:170 contains commented-out code for no apparent reason
> 
> 
> Basic functionality seems good, after these changes :D

Fixed

**Comment by ArcticCoder** [comment]
> > The way the indices are handled right now doesn't work. The clicked index becomes invalid as soon as the filtering changes, but this is not handled in the code, leading to panics. Example:
> > ```
> > 1. Start program
> > 
> > 2. Solve empty sudoku
> > 
> > 3. Click a constraint
> > 
> > 4. Filter with a max length of 5
> > 
> > 5. Line 27 of sudoku_grid.rs panics with an index-out-of-bounds
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Additionally
> > ```
> > * The numbers seem very small to me, even more so when considering a lecture-type setting.
> > 
> > * src/gui/constraint_list.rs:170 contains commented-out code for no apparent reason
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Basic functionality seems good, after these changes :D
> 
> Fixed

The same problem occurs if you click on a square to do the filtering. And the same problem will pop back up each and every time we add another method for filtering. Currently, when you click on a square it at best changes the selected constraint, at worst panics.

Other fixes seem good.

**Comment by ArcticCoder** [comment]
This version breaks the filter system entirely.

1. It updates the internal filter state, without recreating rendered_constraints
2.  As a result filtering by length, for example, is undone when you click a constraint. The next time the list is rebuilt (like when you click on a square), the list is no longer filtered correctly

**Review by ArcticCoder — APPROVED** [review]

**Pull request merged**
