### PR TITLE
Implement trail exporting to cadical

### PR DESCRIPTION
**Pull request by pavezzo**
* Add cadical-rs to project as a lib
* Implement trail exporting to cadical
* Implement rust interface for trail exporting

To view changes I did to cadical and cadical-rs search for PAAVO inside cadical-rs

### CODE REVIEW

**Review by ArcticCoder — COMMENTED** [review]
As far as I understood it, the intention is to save the trail when cadical encounters a contradiction during solving (i.e. when something is learned), but this might be something to bring up during the next customer meeting. I don't think this should be merged right now, as only having the final trail doesn't tell us all that much.

However, great work on setting up the project to allow us to customize cadical! :D

**Comment by pavezzo** [comment]
> As far as I understood it, the intention is to save the trail when cadical encounters a contradiction during solving (i.e. when something is learned), but this might be something to bring up during the next customer meeting. I don't think this should be merged right now, as only having the final trail doesn't tell us all that much.
> 
> However, great work on setting up the project to allow us to customize cadical! :D

So what you are saying is that every time cadical exports learned clause we should also export the 2 conflict literals and the trail?

**Comment by ArcticCoder** [comment]
> > As far as I understood it, the intention is to save the trail when cadical encounters a contradiction during solving (i.e. when something is learned), but this might be something to bring up during the next customer meeting. I don't think this should be merged right now, as only having the final trail doesn't tell us all that much.
> > However, great work on setting up the project to allow us to customize cadical! :D
> 
> So what you are saying is that every time cadical exports learned clause we should also export the 2 conflict literals and the trail?

I believe that is what the customer wanted yes, but we'll know for sure on monday.

**Review by ArcticCoder — APPROVED** [review]
I'll hold off on merging for now, until the next sprint. At that point we might also change the base from `main` to `develop`, `staging` or whatever the new branch ends up being.

Already marking as approved as the content is good, great work! :)

**Pull request merged**
