### PR TITLE
Center and contain sudoku grid

### PR DESCRIPTION
**Pull request by HeljaeRaeisaenen**
I set a minimum size for the app window, centered the sudoku grid in its column, and made the buttons etc. in the left column wrap around to keep them from being hidden behind the sudoku on small window sizes. As a result, the smallest window looks like this:

image

And when there's space around the sudoku on either the y or x axis, the sudoku sits in the middle:

image

I achieved this by calculating the point for the upper left corner of the sudoku based on the parent column's height and width.

I also modified the filtering input field to be much smaller, but long enough to show three digits. 

If something should be still modified I can do it.

### CODE REVIEW

**Comment by HeljaeRaeisaenen** [comment]
So the codecov checks failed because I modified `main.rs`, adding several lines that are not covered by the tests. I made changes to the eframe options and I don't think this code can be moved elsewhere. What can I do?

**Comment by pavezzo** [comment]
> So the codecov checks failed because I modified `main.rs`, adding several lines that are not covered by the tests. I made changes to the eframe options and I don't think this code can be moved elsewhere. What can I do?

Adding main.rs behind --ignore flag like gui in ci.yml should work

**Comment by HeljaeRaeisaenen** [comment]
> > So the codecov checks failed because I modified `main.rs`, adding several lines that are not covered by the tests. I made changes to the eframe options and I don't think this code can be moved elsewhere. What can I do?
> 
> Adding main.rs behind --ignore flag like gui in ci.yml should work

Can I do it directly to main or do I need to do it in ci-testing branch?

**Review by ArcticCoder — APPROVED** [review]
Small but significant fixes. Thanks! :D

**Pull request merged**
