### PR TITLE
Graphical sudoku input

### PR DESCRIPTION
**Pull request by lxhelmer**
Adds the ability to create the starting sudoku using the grid.
There are no tests since the functionality is almost exclusively in gui.

### CODE REVIEW

**Review by HeljaeRaeisaenen — CHANGES_REQUESTED** [review]
Looks mostly good, but
- run linter and formatter, there CI run failed because of compiler warnings
- there are some debug prints and commented out prints left in the code, these should maybe be removed
- the red RECORDING text may not fit the ui style? Maybe it should say "Input mode" or "Create a sudoku" or something, and be a bit smaller and not red like an error, in my opinion.
- when inputting a sudoku, there should be way to remove an inputted number, this would be much nicer for the user.

But good work :)

**Comment by lxhelmer** [comment]
Will do, thanks for good input!

**Comment by lxhelmer** [comment]
Prior notices have been taken into consideration. I reworked the input mode identifier, not perfect but probably good for now.

**Review by HeljaeRaeisaenen — COMMENTED** [review]
`src/gui/constraint_list.rs` line 57 prints the directory of the chosen sudoku file. Is this intentional? Looks like a forgotten debug print. Otherwise everything is looking perfect.

**Review by HeljaeRaeisaenen — APPROVED** [review]
Everything is perfect

**Pull request merged**
